/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    cities: City;
    sources: Source;
    locations: Location;
    'crawl-jobs': CrawlJob;
    'crawl-logs': CrawlLog;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    sources: SourcesSelect<false> | SourcesSelect<true>;
    locations: LocationsSelect<false> | LocationsSelect<true>;
    'crawl-jobs': CrawlJobsSelect<false> | CrawlJobsSelect<true>;
    'crawl-logs': CrawlLogsSelect<false> | CrawlLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      runCrawl: TaskRunCrawl;
      scheduleCrawl: TaskScheduleCrawl;
      scheduleTransitCrawl: TaskScheduleTransitCrawl;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Cấu hình tỉnh/thành cho map + crawl. Hardcode trong code chỉ còn seed/fallback khi DB trống.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  /**
   * Slug ổn định (hanoi, hcm, …) — crawler/API dùng field này.
   */
  code: string;
  name: string;
  latitude: number;
  longitude: number;
  zoom: number;
  bbox: {
    minLat: number;
    maxLat: number;
    minLng: number;
    maxLng: number;
  };
  /**
   * Tắt để ẩn khỏi map switcher / không crawl mặc định.
   */
  enabled?: boolean | null;
  /**
   * Thứ tự hiển thị (nhỏ hơn = trước).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * CMS mirror — dữ liệu crawl production nằm ở bảng SQL `sources` (migration).
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources".
 */
export interface Source {
  id: number;
  name: string;
  type: 'official_website' | 'openstreetmap' | 'external_api' | 'other';
  url?: string | null;
  status: 'active' | 'inactive';
  lastCrawledAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * CMS mirror — map public đọc bảng SQL `locations` qua /api/locations.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations".
 */
export interface Location {
  id: number;
  name: string;
  type:
    | 'charging_station'
    | 'store'
    | 'service_center'
    | 'showroom'
    | 'dealer'
    | 'parking'
    | 'rescue_team'
    | 'gas_station'
    | 'university'
    | 'hospital'
    | 'pharmacy'
    | 'atm'
    | 'bank'
    | 'police'
    | 'fire_station'
    | 'school'
    | 'marketplace'
    | 'bus_stop'
    | 'subway_station'
    | 'park'
    | 'tourist_attraction';
  address: string;
  latitude: number;
  longitude: number;
  status: 'active' | 'inactive';
  phone?: string | null;
  openingHours?: string | null;
  source: number | Source;
  sourceRecordId?: string | null;
  sourceUrl?: string | null;
  lastSeenAt?: string | null;
  lastUpdated?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Manual: Create → Save (Pending) để crawl ngay. Auto map POI: scheduleCrawl. Auto điểm dừng: scheduleTransitCrawl (HN + HCM, bus_stop+subway, mỗi 4h). Queue tuần tự. Debug: Payload Jobs.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crawl-jobs".
 */
export interface CrawlJob {
  id: number;
  /**
   * Tiêu đề list Admin (tự sinh nếu để trống).
   */
  label?: string | null;
  /**
   * Thành phố cần crawl (từ Cities).
   */
  cities: (number | City)[];
  /**
   * Mặc định = đủ loại trên bản đồ (vinfast + Overpass). Tương ứng CRAWL_SOURCES Python.
   */
  crawlSources: (
    | 'vinfast'
    | 'charging'
    | 'parking'
    | 'rescue'
    | 'gas'
    | 'university'
    | 'hospital'
    | 'pharmacy'
    | 'atm'
    | 'bank'
    | 'police'
    | 'fire_station'
    | 'school'
    | 'marketplace'
    | 'bus_stop'
    | 'subway_station'
    | 'park'
    | 'tourist_attraction'
  )[];
  trigger: 'manual' | 'schedule';
  /**
   * Legacy CMS mirror (optional). Job mới dùng crawlSources.
   */
  source?: (number | null) | Source;
  startedAt?: string | null;
  finishedAt?: string | null;
  status: 'pending' | 'running' | 'success' | 'failed';
  recordsFound?: number | null;
  recordsCreated?: number | null;
  recordsUpdated?: number | null;
  recordsDeactivated?: number | null;
  errorMessage?: string | null;
  /**
   * Stdout/stderr rút gọn từ lần chạy crawler gần nhất.
   */
  logTail?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crawl-logs".
 */
export interface CrawlLog {
  id: number;
  crawlJob: number | CrawlJob;
  level: 'INFO' | 'WARNING' | 'ERROR';
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * Payload Jobs Queue — runCrawl + scheduleCrawl + scheduleTransitCrawl (HN/HCM transit every 4h). Debug retries/failures.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'runCrawl' | 'scheduleCrawl' | 'scheduleTransitCrawl';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'runCrawl' | 'scheduleCrawl' | 'scheduleTransitCrawl') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'sources';
        value: number | Source;
      } | null)
    | ({
        relationTo: 'locations';
        value: number | Location;
      } | null)
    | ({
        relationTo: 'crawl-jobs';
        value: number | CrawlJob;
      } | null)
    | ({
        relationTo: 'crawl-logs';
        value: number | CrawlLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  latitude?: T;
  longitude?: T;
  zoom?: T;
  bbox?:
    | T
    | {
        minLat?: T;
        maxLat?: T;
        minLng?: T;
        maxLng?: T;
      };
  enabled?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sources_select".
 */
export interface SourcesSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  url?: T;
  status?: T;
  lastCrawledAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "locations_select".
 */
export interface LocationsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  address?: T;
  latitude?: T;
  longitude?: T;
  status?: T;
  phone?: T;
  openingHours?: T;
  source?: T;
  sourceRecordId?: T;
  sourceUrl?: T;
  lastSeenAt?: T;
  lastUpdated?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crawl-jobs_select".
 */
export interface CrawlJobsSelect<T extends boolean = true> {
  label?: T;
  cities?: T;
  crawlSources?: T;
  trigger?: T;
  source?: T;
  startedAt?: T;
  finishedAt?: T;
  status?: T;
  recordsFound?: T;
  recordsCreated?: T;
  recordsUpdated?: T;
  recordsDeactivated?: T;
  errorMessage?: T;
  logTail?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "crawl-logs_select".
 */
export interface CrawlLogsSelect<T extends boolean = true> {
  crawlJob?: T;
  level?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: number;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskRunCrawl".
 */
export interface TaskRunCrawl {
  input: {
    crawlJobId: string;
  };
  output: {
    status?: string | null;
    exitCode?: number | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskScheduleCrawl".
 */
export interface TaskScheduleCrawl {
  input?: unknown;
  output: {
    crawlJobIds?: string | null;
    cities?: number | null;
    sources?: number | null;
    mode?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskScheduleTransitCrawl".
 */
export interface TaskScheduleTransitCrawl {
  input?: unknown;
  output: {
    crawlJobIds?: string | null;
    cities?: number | null;
    sources?: number | null;
    mode?: string | null;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}